allow-branch = ["main"]
sign-commit = false
sign-tag = false
push = true
publish = false
tag-prefix = "v"
tag-name = "{{prefix}}{{version}}"
pre-release-commit-message = "chore: release {{version}}"
tag-message = "{{version}}"

pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}", exactly = 1 },
]
